// Generated by jextract

package it.auties.leap.impl.win;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*LPWSAOVERLAPPED_COMPLETION_ROUTINE)(DWORD, DWORD, LPWSAOVERLAPPED, DWORD) __attribute__((stdcall))
 * }
 */
public class LPWSAOVERLAPPED_COMPLETION_ROUTINE {

    LPWSAOVERLAPPED_COMPLETION_ROUTINE() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(int dwError, int cbTransferred, MemorySegment lpOverlapped, int dwFlags);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        WindowsSockets.C_LONG,
        WindowsSockets.C_LONG,
        WindowsSockets.C_POINTER,
        WindowsSockets.C_LONG
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = WindowsSockets.upcallHandle(LPWSAOVERLAPPED_COMPLETION_ROUTINE.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(LPWSAOVERLAPPED_COMPLETION_ROUTINE.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr,int dwError, int cbTransferred, MemorySegment lpOverlapped, int dwFlags) {
        try {
             DOWN$MH.invokeExact(funcPtr, dwError, cbTransferred, lpOverlapped, dwFlags);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

