// Generated by jextract

package it.auties.leap.socket.common.win;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang=c :
 * typedef BOOL (*LPFN_CONNECTEX)(SOCKET, const struct sockaddr {
 *     ADDRESS_FAMILY sa_family;
 *     CHAR sa_data[14];
 * } *, int, PVOID, DWORD, LPDWORD, LPOVERLAPPED) __attribute__((stdcall))
 * }
 */
public class LPFN_CONNECTEX {

    LPFN_CONNECTEX() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(long s, MemorySegment name, int namelen, MemorySegment lpSendBuffer, int dwSendDataLength, MemorySegment lpdwBytesSent, MemorySegment lpOverlapped);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        WindowsKernel.C_INT,
        WindowsKernel.C_LONG_LONG,
        WindowsKernel.C_POINTER,
        WindowsKernel.C_INT,
        WindowsKernel.C_POINTER,
        WindowsKernel.C_LONG,
        WindowsKernel.C_POINTER,
        WindowsKernel.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = WindowsKernel.upcallHandle(Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,long s, MemorySegment name, int namelen, MemorySegment lpSendBuffer, int dwSendDataLength, MemorySegment lpdwBytesSent, MemorySegment lpOverlapped) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, s, name, namelen, lpSendBuffer, dwSendDataLength, lpdwBytesSent, lpOverlapped);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

