package it.auties.leap.tls.message;

public enum TlsMessageType {
    ALERT,
    APPLICATION_DATA,

    SERVER_HELLO_REQUEST,
    SERVER_HELLO,
    SERVER_CERTIFICATE,
    SERVER_CERTIFICATE_REQUEST,
    SERVER_KEY_EXCHANGE,
    SERVER_CHANGE_CIPHER_SPEC,
    SERVER_HELLO_DONE,
    SERVER_FINISHED,

    CLIENT_HELLO,
    CLIENT_CERTIFICATE,
    CLIENT_KEY_EXCHANGE,
    CLIENT_CERTIFICATE_VERIFY,
    CLIENT_CHANGE_CIPHER_SPEC,
    CLIENT_FINISHED,

    RESERVED
}
