package it.auties.leap.tls.ciphersuite.exchange.implementation;

import it.auties.leap.tls.alert.TlsAlert;
import it.auties.leap.tls.alert.TlsAlertLevel;
import it.auties.leap.tls.alert.TlsAlertType;
import it.auties.leap.tls.certificate.TlsCertificate;
import it.auties.leap.tls.ciphersuite.exchange.TlsKeyExchange;
import it.auties.leap.tls.ciphersuite.exchange.TlsKeyExchangeFactory;
import it.auties.leap.tls.ciphersuite.exchange.TlsKeyExchangeType;
import it.auties.leap.tls.connection.TlsConnection;
import it.auties.leap.tls.connection.TlsConnectionSecret;
import it.auties.leap.tls.context.TlsContext;
import it.auties.leap.tls.context.TlsContextualProperty;
import it.auties.leap.tls.ec.TlsEcCurveType;
import it.auties.leap.tls.group.TlsSupportedEllipticCurve;
import it.auties.leap.tls.group.TlsSupportedGroupKeys;
import org.bouncycastle.jcajce.interfaces.XDHPublicKey;
import org.bouncycastle.jce.interfaces.ECPublicKey;

import java.nio.ByteBuffer;
import java.security.interfaces.XECPublicKey;
import java.util.Optional;

import static it.auties.leap.tls.util.BufferUtils.*;

public sealed abstract class ECDHKeyExchange implements TlsKeyExchange {
    private static final TlsKeyExchangeFactory STATIC = new ECDHKeyExchangeFactory(TlsKeyExchangeType.STATIC);
    private static final TlsKeyExchangeFactory EPHEMERAL = new ECDHKeyExchangeFactory(TlsKeyExchangeType.EPHEMERAL);

    public static TlsKeyExchangeFactory staticFactory() {
        return STATIC;
    }

    public static TlsKeyExchangeFactory ephemeralFactory() {
        return EPHEMERAL;
    }

    final TlsKeyExchangeType type;
    private ECDHKeyExchange(TlsKeyExchangeType type) {
        this.type = type;
    }

    @Override
    public TlsKeyExchangeType type() {
        return type;
    }

    @Override
    public TlsConnectionSecret generatePreSharedSecret(TlsContext context) {
        var group = context.localConnectionState()
                .ephemeralKeyPair()
                .orElseThrow(() -> new TlsAlert(
                        "Cannot generate pre shared secret: no ephemeral key pair was selected",
                        TlsAlertLevel.FATAL,
                        TlsAlertType.HANDSHAKE_FAILURE
                ))
                .group();
        if(!(group instanceof TlsSupportedEllipticCurve)) {
            throw new TlsAlert(
                    "Cannot generate pre shared secret: selected ephemeral key pair was generated by a group that isn't an elliptic curve",
                    TlsAlertLevel.FATAL,
                    TlsAlertType.HANDSHAKE_FAILURE
            );
        }
        return group.computeSharedSecret(context);
    }

    public abstract Optional<TlsEcCurveType> parameters();

    private static final class Client extends ECDHKeyExchange {
        private final byte[] publicKey;

        private Client(TlsKeyExchangeType type, byte[] publicKey) {
            super(type);
            this.publicKey = publicKey;
        }

        @Override
        public void serialize(ByteBuffer buffer) {
            writeBytesBigEndian8(buffer, publicKey);
        }

        @Override
        public int length() {
            return INT8_LENGTH + publicKey.length;
        }

        @Override
        public Optional<TlsEcCurveType> parameters() {
            return Optional.empty();
        }
    }

    private static final class Server extends ECDHKeyExchange {
        private final TlsEcCurveType parameters;
        private final byte[] publicKey;

        private Server(TlsKeyExchangeType type, TlsEcCurveType parameters, byte[] publicKey) {
            super(type);
            this.parameters = parameters;
            this.publicKey = publicKey;
        }

        @Override
        public void serialize(ByteBuffer buffer) {
            writeBytesBigEndian8(buffer, publicKey);
        }

        @Override
        public int length() {
            return parameters.length()
                    + INT8_LENGTH + publicKey.length;
        }

        @Override
        public Optional<TlsEcCurveType> parameters() {
            return Optional.ofNullable(parameters);
        }
    }

    private record ECDHKeyExchangeFactory(TlsKeyExchangeType type) implements TlsKeyExchangeFactory {
        @Override
        public Optional<TlsKeyExchange> newLocalKeyExchange(TlsContext context) {
            var connectionState = context.localConnectionState();
            return switch (type) {
                case STATIC -> {
                    var certificate = getStaticCertificate(connectionState).orElseThrow(() -> new TlsAlert(
                            "Cannot generate static key exchange: no local ECDH key was provided",
                            TlsAlertLevel.FATAL,
                            TlsAlertType.HANDSHAKE_FAILURE
                    ));
                    var result = connectionState.chooseStaticCertificate(certificate);
                    if(!result) {
                        throw new TlsAlert(
                                "Cannot generate static key exchange: selected DH certificate doesn't exist",
                                TlsAlertLevel.FATAL,
                                TlsAlertType.HANDSHAKE_FAILURE
                        );
                    }
                    yield Optional.empty();
                }

                case EPHEMERAL -> switch (context.localConnectionState().type()) {
                    case CLIENT -> {
                        var remoteKeyExchange = context.remoteConnectionState()
                                .orElseThrow(() -> new TlsAlert(
                                        "Cannot generate ephemeral client key exchange: no remote server connection state was created",
                                        TlsAlertLevel.FATAL,
                                        TlsAlertType.HANDSHAKE_FAILURE
                                ))
                                .keyExchange()
                                .orElseThrow(() -> new TlsAlert(
                                        "Cannot generate ephemeral client key exchange: no remote server key exchange was created",
                                        TlsAlertLevel.FATAL,
                                        TlsAlertType.HANDSHAKE_FAILURE
                                ));
                        if(!(remoteKeyExchange instanceof Server remoteEcdhKeyExchange)) {
                            throw new TlsAlert(
                                    "Cannot generate ephemeral client key exchange: remote key exchange isn't a server ECDH key exchange",
                                    TlsAlertLevel.FATAL,
                                    TlsAlertType.HANDSHAKE_FAILURE
                            );
                        }
                        var negotiatedGroup = remoteEcdhKeyExchange.parameters()
                                .orElseThrow(() -> new TlsAlert(
                                        "Cannot generate ephemeral client key exchange: remote key exchange doesn't provide parameters",
                                        TlsAlertLevel.FATAL,
                                        TlsAlertType.HANDSHAKE_FAILURE
                                ))
                                .toGroup(context);
                        var keyPair = negotiatedGroup.generateKeyPair(context);
                        var result = context.localConnectionState()
                                .addEphemeralKeyPair(TlsSupportedGroupKeys.of(negotiatedGroup, keyPair))
                                .chooseEphemeralKeyPair(negotiatedGroup);
                        if(!result) {
                            throw new TlsAlert(
                                    "Cannot generate ephemeral client key exchange: selected ephemeral ECDH key pair doesn't exist",
                                    TlsAlertLevel.FATAL,
                                    TlsAlertType.HANDSHAKE_FAILURE
                            );
                        }
                        var publicKey = negotiatedGroup.dumpPublicKey(keyPair.getPublic());
                        var localKeyExchange = new Client(type, publicKey);
                        yield Optional.of(localKeyExchange);
                    }
                    case SERVER -> {
                        var preferredGroup = context.getNegotiatedValue(TlsContextualProperty.supportedGroups())
                                .orElseThrow(() -> new TlsAlert(
                                        "Cannot generate ephemeral server key exchange: no supported groups were negotiated",
                                        TlsAlertLevel.FATAL,
                                        TlsAlertType.HANDSHAKE_FAILURE
                                ))
                                .stream()
                                .filter(supportedGroup -> supportedGroup instanceof TlsSupportedEllipticCurve)
                                .map(supportedGroup -> (TlsSupportedEllipticCurve) supportedGroup)
                                .findFirst()
                                .orElseThrow(() -> new TlsAlert(
                                        "Cannot generate ephemeral server key exchange: no negotiated supported group is an elliptic curve",
                                        TlsAlertLevel.FATAL,
                                        TlsAlertType.HANDSHAKE_FAILURE
                                ));
                        var keyPair = preferredGroup.generateKeyPair(context);
                        var result = context.localConnectionState()
                                .addEphemeralKeyPair(TlsSupportedGroupKeys.of(preferredGroup, keyPair))
                                .chooseEphemeralKeyPair(preferredGroup);
                        if(!result) {
                            throw new TlsAlert(
                                    "Cannot generate ephemeral server key exchange: selected ephemeral ECDH key pair doesn't exist",
                                    TlsAlertLevel.FATAL,
                                    TlsAlertType.HANDSHAKE_FAILURE
                            );
                        }
                        var parameters = preferredGroup.toParameters();
                        var publicKey = preferredGroup.dumpPublicKey(keyPair.getPublic());
                        var localKeyExchange = new Server(type, parameters, publicKey);
                        yield Optional.of(localKeyExchange);
                    }
                };
            };
        }

        @Override
        public Optional<TlsKeyExchange> newRemoteKeyExchange(TlsContext context, ByteBuffer source) {
            return switch (type) {
                case STATIC -> {
                    if(source != null) {
                        throw new TlsAlert(
                                "Cannot generate static key exchange: received unexpected key exchange source",
                                TlsAlertLevel.FATAL,
                                TlsAlertType.INTERNAL_ERROR
                        );
                    }

                    var connectionState = context.remoteConnectionState().orElseThrow(() -> new TlsAlert(
                            "Cannot generate static key exchange: no remote server connection state was created",
                            TlsAlertLevel.FATAL,
                            TlsAlertType.HANDSHAKE_FAILURE
                    ));
                    var certificate = getStaticCertificate(connectionState).orElseThrow(() -> new TlsAlert(
                            "Cannot generate static key exchange: no remote ECDH key was received",
                            TlsAlertLevel.FATAL,
                            TlsAlertType.HANDSHAKE_FAILURE
                    ));
                    var result = connectionState.chooseStaticCertificate(certificate);
                    if(!result) {
                        throw new TlsAlert(
                                "Cannot generate static key exchange: selected DH certificate doesn't exist",
                                TlsAlertLevel.FATAL,
                                TlsAlertType.HANDSHAKE_FAILURE
                        );
                    }
                    yield Optional.empty();
                }

                case EPHEMERAL -> {
                    if(source == null) {
                        throw new TlsAlert(
                                "Cannot generate ephemeral key exchange: received null key exchange source",
                                TlsAlertLevel.FATAL,
                                TlsAlertType.INTERNAL_ERROR
                        );
                    }

                    var connectionState = context.remoteConnectionState().orElseThrow(() -> new TlsAlert(
                            "Cannot generate ephemeral key exchange: no remote server connection state was created",
                            TlsAlertLevel.FATAL,
                            TlsAlertType.HANDSHAKE_FAILURE
                    ));
                    yield switch (connectionState.type()) {
                        case CLIENT -> {
                            var y = readBytesBigEndian8(source);
                            var preferredGroup = context.getNegotiatedValue(TlsContextualProperty.supportedGroups())
                                    .orElseThrow(() -> new TlsAlert(
                                            "Cannot generate ephemeral client key exchange: no supported groups were negotiated",
                                            TlsAlertLevel.FATAL,
                                            TlsAlertType.HANDSHAKE_FAILURE
                                    ))
                                    .stream()
                                    .filter(supportedGroup -> supportedGroup instanceof TlsSupportedEllipticCurve)
                                    .map(supportedGroup -> (TlsSupportedEllipticCurve) supportedGroup)
                                    .findFirst()
                                    .orElseThrow(() -> new TlsAlert(
                                            "Cannot generate ephemeral client key exchange: no negotiated supported group is an elliptic curve",
                                            TlsAlertLevel.FATAL,
                                            TlsAlertType.HANDSHAKE_FAILURE
                                    ));
                            var remotePublicKey = preferredGroup.parsePublicKey(y);
                            var result = connectionState.addEphemeralKeyPair(TlsSupportedGroupKeys.of(preferredGroup, remotePublicKey))
                                    .chooseEphemeralKeyPair(preferredGroup);
                            if(!result) {
                                throw new TlsAlert(
                                        "Cannot generate ephemeral client key exchange: selected ephemeral ECDH key pair doesn't exist",
                                        TlsAlertLevel.FATAL,
                                        TlsAlertType.HANDSHAKE_FAILURE
                                );
                            }
                            var remoteKeyExchange = new Client(type, y);
                            yield Optional.of(remoteKeyExchange);
                        }
                        case SERVER -> {
                            var ecType = readBigEndianInt8(source);
                            var negotiatedGroup = context.getNegotiatedValue(TlsContextualProperty.supportedGroups())
                                    .orElseThrow(() -> new TlsAlert(
                                            "Cannot generate ephemeral server key exchange: no supported groups were negotiated",
                                            TlsAlertLevel.FATAL,
                                            TlsAlertType.HANDSHAKE_FAILURE
                                    ))
                                    .stream()
                                    .filter(supportedGroup -> supportedGroup instanceof TlsSupportedEllipticCurve supportedEllipticCurve
                                            && ecType == supportedEllipticCurve.parametersDeserializer().id())
                                    .map(supportedGroup -> (TlsSupportedEllipticCurve) supportedGroup)
                                    .findFirst()
                                    .orElseThrow(() -> new TlsAlert(
                                            "Cannot generate ephemeral server key exchange: no negotiated supported group that is an elliptic curve accepts the server key exchange",
                                            TlsAlertLevel.FATAL,
                                            TlsAlertType.HANDSHAKE_FAILURE
                                    ));
                            var parameters = negotiatedGroup.parametersDeserializer()
                                    .deserialize(source);
                            var y = readBytesBigEndian8(source);
                            var publicKey = negotiatedGroup.parsePublicKey(y);
                            var result = connectionState.addEphemeralKeyPair(TlsSupportedGroupKeys.of(negotiatedGroup, publicKey))
                                    .chooseEphemeralKeyPair(negotiatedGroup);
                            if(!result) {
                                throw new TlsAlert(
                                        "Cannot generate ephemeral server key exchange: selected ephemeral ECDH key pair doesn't exist",
                                        TlsAlertLevel.FATAL,
                                        TlsAlertType.HANDSHAKE_FAILURE
                                );
                            }
                            var remoteKeyExchange = new Server(type, parameters, y);
                            yield Optional.of(remoteKeyExchange);
                        }
                    };
                }
            };
        }

        // TODO: Check this method
        private Optional<TlsCertificate> getStaticCertificate(TlsConnection connectionState) {
            return connectionState.certificates()
                    .stream()
                    .filter(entry -> {
                        var publicKey = entry.value().getPublicKey();
                        return publicKey instanceof XDHPublicKey
                                || publicKey instanceof XECPublicKey
                                || publicKey instanceof ECPublicKey;
                    })
                    .findFirst();
        }
    }
}
